CREATE TABLE categories (
  id serial PRIMARY KEY,
  title VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE money_subs (
id serial NOT NULL,
date_sub DATE NOT NULL,
amount NUMERIC(8, 2) NOT NULL,
description VARCHAR(50),
category_id INTEGER NOT NULL REFERENCES categories(id)
);

INSERT INTO categories (title) VALUES ('bills');
INSERT INTO categories (title) VALUES ('food');
INSERT INTO categories (title) VALUES ('clothing');
INSERT INTO categories (title) VALUES ('entertainment');
INSERT INTO categories (title) VALUES ('transportation');
INSERT INTO categories (title) VALUES ('misc');

INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-12-03', 57, 'Lumbersexual plaid neutra.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-14', 137, 'Portland bushwick slow-carb.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-05', 112, 'Heirloom actually lo-fi.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-26', 177, 'Bushwick cardigan meggings.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-11-14', 43, 'Organic tilde seitan.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-25', 74, 'Meh carry artisan.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-12-25', 85, 'Venmo diy letterpress.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-09-25', 20, 'Typewriter butcher vegan.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-06-22', 36, 'Gastropub diy neutra.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-06-22', 180, 'Loko gentrify forage.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-02-17', 142, 'Kinfolk occupy blog.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-03-24', 70, 'Post-ironic banjo cleanse.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-12-28', 13, 'Microdosing offal pour-over.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-04-01', 116, 'Ugh bushwick loko.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-07', 173, 'Franzen tattooed try-hard.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-11', 118, 'Migas polaroid roof.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-13', 100, 'Kogi semiotics chambray.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-10-09', 128, 'Pinterest freegan butcher.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-18', 26, 'Ugh cred mlkshk.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-15', 122, 'Readymade paleo pitchfork.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-05', 38, 'Farm-to-table quinoa yuccie.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-02-04', 93, 'Offal biodiesel plaid.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-18', 122, 'Flannel vegan listicle.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-12', 153, 'Chicharrones lomo bitters.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-04-07', 23, 'Vhs banjo quinoa.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-05-24', 73, 'Flannel intelligentsia meh.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-03-03', 76, 'Cold-pressed readymade pinterest.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-04-09', 106, 'Dreamcatcher park church-key.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-02-06', 47, 'Lo-fi etsy sriracha.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-10', 103, 'Twee master stumptown.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-17', 159, 'Plaid meh humblebrag.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-04', 24, 'Aesthetic mumblecore locavore.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-03-23', 56, 'Church-key hashtag quinoa.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-08-26', 56, 'Lomo xoxo dreamcatcher.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-05-21', 133, 'Sustainable organic knausgaard.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-05-14', 11, 'Tofu flannel chillwave.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-12-19', 117, 'Crucifix hella salvia.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-05-23', 26, 'Vhs xoxo locavore.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-04-26', 156, 'Pbr&b bushwick hammock.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-12-05', 110, 'Keffiyeh gentrify ennui.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-01', 90, 'Forage pinterest locavore.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-09', 21, 'Polaroid goth slow-carb.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-04-19', 150, 'Butcher schlitz literally.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-12-09', 161, 'Neutra umami cleanse.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-03-21', 12, 'Irony chillwave ugh.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-09-07', 180, 'Butcher sartorial master.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-09-11', 149, 'Vinyl tousled squid.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-03-07', 102, 'Chia blog seitan.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-10-19', 13, 'Carry heirloom listicle.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-08-23', 95, 'Offal readymade vinegar.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-10', 177, 'Butcher seitan synth.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-10-19', 62, 'Butcher locavore chartreuse.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-02-21', 45, 'Listicle plaid cold-pressed.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-04-26', 133, 'Chillwave banjo drinking.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-10-10', 6, 'Chicharrones carry neutra.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-03-02', 105, 'Polaroid hammock vegan.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-03-09', 151, 'Flexitarian narwhal waistcoat.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-14', 152, 'Iphone squid selvage.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-11-13', 95, 'Neutra helvetica butcher.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-02-06', 62, 'Kickstarter echo church-key.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-04-23', 86, 'Farm-to-table leggings taxidermy.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-01-23', 162, 'Tacos selvage readymade.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-02-03', 150, 'Pug pinterest bushwick.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-06-05', 47, 'Organic ethical brunch.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-02-02', 78, 'Fap forage letterpress.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-07-04', 143, 'Fap swag hoodie.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-05-18', 174, 'Lomo sriracha yuccie.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-10-23', 179, 'Stumptown cliche letterpress.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-09-08', 69, 'Cardigan poutine banjo.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-04-04', 180, 'Pitchfork kickstarter kinfolk.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-06', 24, 'Post-ironic seitan meh.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-06-13', 29, 'Schlitz distillery kogi.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-28', 25, 'Ugh yuccie freegan.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-08-13', 173, 'Mumblecore listicle swag.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-06-01', 27, 'Hella migas keffiyeh.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-09-17', 54, 'Retro cray hella.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-10-15', 132, 'Pinterest wayfarers lo-fi.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-01-15', 61, 'Pitchfork ugh +1.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-06-08', 138, 'Scenester letterpress pinterest.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-05-19', 59, 'Taxidermy sriracha synth.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-06-06', 100, 'Cold-pressed mlkshk twee.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-07-12', 123, 'Locavore etsy asymmetrical.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-04-28', 99, 'Pour-over cliche hashtag.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-11-03', 179, 'Disrupt taxidermy intelligentsia.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-02-25', 36, 'Pug meditation tofu.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-03', 82, 'Vhs vinegar polaroid.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-06-16', 169, 'Whatever yr schlitz.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-03-06', 128, 'Fixie park vice.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-01-25', 88, 'Bushwick freegan gastropub.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-18', 75, 'Swag iphone butcher.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-08-05', 93, 'Selvage chambray schlitz.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-07-06', 18, 'Shoreditch dreamcatcher squid.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-05-12', 100, 'Locavore poutine franzen.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-02-01', 46, 'Ugh cold-pressed occupy.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-02-21', 104, 'Williamsburg health slow-carb.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-03-02', 48, 'Bespoke etsy selvage.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-06', 108, 'Narwhal literally ennui.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-18', 56, 'Post-ironic vinegar chartreuse.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-23', 57, 'Portland artisan kitsch.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-12-26', 105, 'Actually ugh tilde.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-03', 33, 'Blog loko selvage.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-09-25', 77, 'Brunch wolf lo-fi.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-01-23', 85, 'Knausgaard goth tumblr.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-11-11', 99, 'Roof freegan pug.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-02-16', 167, 'Humblebrag lo-fi authentic.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-26', 62, 'Mustache plaid waistcoat.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-10-13', 142, 'Goth semiotics kogi.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-09-13', 156, 'Kitsch lumbersexual authentic.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-06', 118, 'Organic polaroid flannel.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-11-28', 20, 'Microdosing chartreuse hoodie.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-07-15', 149, 'Ugh locavore chicharrones.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-03-03', 143, 'Roof cray typewriter.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-23', 26, 'Forage cleanse pug.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-12-27', 172, 'Neutra keytar locavore.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-13', 94, 'Mumblecore sustainable poutine.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-10-07', 122, 'Chia offal pbr&b.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-07-26', 99, 'Cornhole 90"s heirloom.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-06-06', 97, 'Church-key everyday iphone.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-09-13', 134, 'Letterpress seitan forage.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-04-22', 158, 'Sartorial tofu mlkshk.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-10-05', 80, 'Keytar banjo chartreuse.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-05-19', 45, 'Polaroid post-ironic heirloom.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-10-01', 110, 'Cleanse hella 90"s.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-03-24', 19, 'Etsy yr tofu.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-10-09', 58, 'Vhs tilde forage.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-10-22', 86, 'Beard plaid tattooed.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-25', 131, 'Authentic quinoa pabst.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-05-24', 171, 'Semiotics taxidermy tofu.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-03-18', 54, 'Selfies distillery whatever.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-10-25', 58, 'Street pop-up tattooed.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-13', 151, 'Fixie irony crucifix.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-10-27', 167, 'Pabst health lo-fi.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-06-12', 85, 'Post-ironic sustainable park.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-14', 99, 'Quinoa normcore carry.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-06', 127, 'Fap keytar freegan.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-02', 160, 'Flannel cardigan sriracha.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-09-19', 45, 'Authentic readymade pitchfork.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-10-23', 17, 'Cardigan cardigan lumbersexual.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-06-26', 152, 'Cliche iphone thundercats.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-12', 38, 'Humblebrag health viral.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-10-16', 47, 'Yolo paleo sartorial.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-08-02', 59, 'Synth truffaut loko.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-12-18', 89, 'Brunch squid salvia.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-20', 46, 'Paleo pabst 8-bit.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-01-14', 133, 'Beard gentrify pabst.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-22', 109, 'Blog bitters cred.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-12-10', 100, 'Helvetica ennui tattooed.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-02-06', 153, 'Vinegar typewriter aesthetic.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-11-16', 21, 'Brooklyn letterpress heirloom.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-02-14', 178, 'Synth kinfolk truffaut.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-09-13', 145, 'Vice goth readymade.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-04-04', 116, 'Pickled 90"s waistcoat.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-23', 158, 'Thundercats church-key slow-carb.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-08-14', 165, 'Freegan yuccie 90"s.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-07', 13, 'Freegan church-key kitsch.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-07-01', 145, 'Chillwave meditation flexitarian.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-07-24', 32, 'Kitsch beard ugh.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-09-17', 70, 'Typewriter twee pinterest.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-11-22', 33, 'Blog authentic irony.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-09-23', 153, 'Chambray polaroid mlkshk.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-02-16', 17, 'Normcore polaroid selvage.', 5 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-04-04', 150, 'Iphone thundercats pickled.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-20', 116, 'Umami pop-up gastropub.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-05-11', 164, 'Salvia readymade health.', 6 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-04-14', 29, 'Stumptown iphone knausgaard.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-09-03', 98, 'Schlitz mustache distillery.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-10-13', 160, 'Fap echo lumbersexual.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-10-09', 129, 'Plaid franzen leggings.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-11-12', 101, 'Hashtag kickstarter pabst.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-16', 144, 'Portland keytar cliche.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-10-06', 29, 'Roof chambray sartorial.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-05-25', 72, 'Mumblecore williamsburg ennui.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-09-25', 133, 'Lomo mumblecore freegan.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-06-13', 150, 'Neutra echo yuccie.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-12-11', 17, 'Fixie umami vhs.', 2 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2015-07-14', 5, 'Cred helvetica readymade.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-01-26', 66, 'Meditation keffiyeh pbr&b.', 3 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-09-23', 102, 'Selvage fixie vegan.', 1 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-09-24', 58, 'Carry tilde stumptown.', 4 );
INSERT INTO money_subs (date_sub, amount, description, category_id) VALUES ('2016-05-27', 51, 'Intelligentsia wolf brooklyn.', 2 );
